/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LearningsRouteImport } from './routes/learnings'
import { Route as GameRouteImport } from './routes/game'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArchitectureCanvasIdRouteImport } from './routes/architecture.$canvasId'
import { Route as ArchitectureCanvasIdIndexRouteImport } from './routes/architecture.$canvasId.index'
import { Route as LearningsFilesFolderIdRouteImport } from './routes/learnings.files.$folderId'
import { Route as LearningsDocsDocIdRouteImport } from './routes/learnings.docs.$docId'
import { Route as LearningsBlogsBlogIdRouteImport } from './routes/learnings.blogs.$blogId'
import { Route as ArchitectureViewViewerIdRouteImport } from './routes/architecture.view.$viewerId'
import { Route as ArchitectureCanvasIdEditRouteImport } from './routes/architecture.$canvasId.edit'
import { Route as LearningsBlogsCreateRouteImport } from './routes/learnings.blogs.create'
import { Route as LearningsBlogsBlogIdEditRouteImport } from './routes/learnings.blogs.$blogId.edit'
import { Route as LearningsDocsCreateRouteImport } from './routes/learnings.docs.create'
import { Route as LearningsDocsDocIdEditRouteImport } from './routes/learnings.docs.$docId.edit'

const LearningsRoute = LearningsRouteImport.update({
  id: '/learnings',
  path: '/learnings',
  getParentRoute: () => rootRouteImport,
} as any)
const GameRoute = GameRouteImport.update({
  id: '/game',
  path: '/game',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchitectureCanvasIdRoute = ArchitectureCanvasIdRouteImport.update({
  id: '/architecture/$canvasId',
  path: '/architecture/$canvasId',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchitectureCanvasIdIndexRoute =
  ArchitectureCanvasIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ArchitectureCanvasIdRoute,
  } as any)
const LearningsFilesFolderIdRoute = LearningsFilesFolderIdRouteImport.update({
  id: '/files/$folderId',
  path: '/files/$folderId',
  getParentRoute: () => LearningsRoute,
} as any)
const LearningsDocsDocIdRoute = LearningsDocsDocIdRouteImport.update({
  id: '/docs/$docId',
  path: '/docs/$docId',
  getParentRoute: () => LearningsRoute,
} as any)
const LearningsBlogsBlogIdRoute = LearningsBlogsBlogIdRouteImport.update({
  id: '/blogs/$blogId',
  path: '/blogs/$blogId',
  getParentRoute: () => LearningsRoute,
} as any)
const ArchitectureViewViewerIdRoute =
  ArchitectureViewViewerIdRouteImport.update({
    id: '/architecture/view/$viewerId',
    path: '/architecture/view/$viewerId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ArchitectureCanvasIdEditRoute =
  ArchitectureCanvasIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => ArchitectureCanvasIdRoute,
  } as any)

const LearningsBlogsCreateRoute = LearningsBlogsCreateRouteImport.update({
  id: '/blogs/create',
  path: '/blogs/create',
  getParentRoute: () => LearningsRoute,
} as any)

const LearningsBlogsBlogIdEditRoute = LearningsBlogsBlogIdEditRouteImport.update({
  id: '/blogs/$blogId/edit',
  path: '/blogs/$blogId/edit',
  getParentRoute: () => LearningsRoute,
} as any)

const LearningsDocsCreateRoute = LearningsDocsCreateRouteImport.update({
  id: '/docs/create',
  path: '/docs/create',
  getParentRoute: () => LearningsRoute,
} as any)

const LearningsDocsDocIdEditRoute = LearningsDocsDocIdEditRouteImport.update({
  id: '/docs/$docId/edit',
  path: '/docs/$docId/edit',
  getParentRoute: () => LearningsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/game': typeof GameRoute
  '/learnings': typeof LearningsRouteWithChildren
  '/architecture/$canvasId': typeof ArchitectureCanvasIdRouteWithChildren
  '/architecture/$canvasId/edit': typeof ArchitectureCanvasIdEditRoute
  '/architecture/view/$viewerId': typeof ArchitectureViewViewerIdRoute
  '/learnings/blogs/$blogId': typeof LearningsBlogsBlogIdRoute
  '/learnings/blogs/create': typeof LearningsBlogsCreateRoute
  '/learnings/blogs/$blogId/edit': typeof LearningsBlogsBlogIdEditRoute
  '/learnings/docs/$docId': typeof LearningsDocsDocIdRoute
  '/learnings/docs/create': typeof LearningsDocsCreateRoute
  '/learnings/docs/$docId/edit': typeof LearningsDocsDocIdEditRoute
  '/learnings/files/$folderId': typeof LearningsFilesFolderIdRoute
  '/architecture/$canvasId/': typeof ArchitectureCanvasIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/game': typeof GameRoute
  '/learnings': typeof LearningsRouteWithChildren
  '/architecture/$canvasId/edit': typeof ArchitectureCanvasIdEditRoute
  '/architecture/view/$viewerId': typeof ArchitectureViewViewerIdRoute
  '/learnings/blogs/$blogId': typeof LearningsBlogsBlogIdRoute
  '/learnings/blogs/create': typeof LearningsBlogsCreateRoute
  '/learnings/blogs/$blogId/edit': typeof LearningsBlogsBlogIdEditRoute
  '/learnings/docs/$docId': typeof LearningsDocsDocIdRoute
  '/learnings/docs/create': typeof LearningsDocsCreateRoute
  '/learnings/docs/$docId/edit': typeof LearningsDocsDocIdEditRoute
  '/learnings/files/$folderId': typeof LearningsFilesFolderIdRoute
  '/architecture/$canvasId': typeof ArchitectureCanvasIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/game': typeof GameRoute
  '/learnings': typeof LearningsRouteWithChildren
  '/architecture/$canvasId': typeof ArchitectureCanvasIdRouteWithChildren
  '/architecture/$canvasId/edit': typeof ArchitectureCanvasIdEditRoute
  '/architecture/view/$viewerId': typeof ArchitectureViewViewerIdRoute
  '/learnings/blogs/$blogId': typeof LearningsBlogsBlogIdRoute
  '/learnings/blogs/create': typeof LearningsBlogsCreateRoute
  '/learnings/blogs/$blogId/edit': typeof LearningsBlogsBlogIdEditRoute
  '/learnings/docs/$docId': typeof LearningsDocsDocIdRoute
  '/learnings/docs/create': typeof LearningsDocsCreateRoute
  '/learnings/docs/$docId/edit': typeof LearningsDocsDocIdEditRoute
  '/learnings/files/$folderId': typeof LearningsFilesFolderIdRoute
  '/architecture/$canvasId/': typeof ArchitectureCanvasIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/game'
    | '/learnings'
    | '/architecture/$canvasId'
    | '/architecture/$canvasId/edit'
    | '/architecture/view/$viewerId'
    | '/learnings/blogs/$blogId'
    | '/learnings/blogs/create'
    | '/learnings/blogs/$blogId/edit'
    | '/learnings/docs/$docId'
    | '/learnings/docs/create'
    | '/learnings/docs/$docId/edit'
    | '/learnings/files/$folderId'
    | '/architecture/$canvasId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/game'
    | '/learnings'
    | '/architecture/$canvasId/edit'
    | '/architecture/view/$viewerId'
    | '/learnings/blogs/$blogId'
    | '/learnings/blogs/create'
    | '/learnings/blogs/$blogId/edit'
    | '/learnings/docs/$docId'
    | '/learnings/docs/create'
    | '/learnings/docs/$docId/edit'
    | '/learnings/files/$folderId'
    | '/architecture/$canvasId'
  id:
    | '__root__'
    | '/'
    | '/game'
    | '/learnings'
    | '/architecture/$canvasId'
    | '/architecture/$canvasId/edit'
    | '/architecture/view/$viewerId'
    | '/learnings/blogs/$blogId'
    | '/learnings/blogs/create'
    | '/learnings/blogs/$blogId/edit'
    | '/learnings/docs/$docId'
    | '/learnings/docs/create'
    | '/learnings/docs/$docId/edit'
    | '/learnings/files/$folderId'
    | '/architecture/$canvasId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GameRoute: typeof GameRoute
  LearningsRoute: typeof LearningsRouteWithChildren
  ArchitectureCanvasIdRoute: typeof ArchitectureCanvasIdRouteWithChildren
  ArchitectureViewViewerIdRoute: typeof ArchitectureViewViewerIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/learnings': {
      id: '/learnings'
      path: '/learnings'
      fullPath: '/learnings'
      preLoaderRoute: typeof LearningsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game': {
      id: '/game'
      path: '/game'
      fullPath: '/game'
      preLoaderRoute: typeof GameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/architecture/$canvasId': {
      id: '/architecture/$canvasId'
      path: '/architecture/$canvasId'
      fullPath: '/architecture/$canvasId'
      preLoaderRoute: typeof ArchitectureCanvasIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/architecture/$canvasId/': {
      id: '/architecture/$canvasId/'
      path: '/'
      fullPath: '/architecture/$canvasId/'
      preLoaderRoute: typeof ArchitectureCanvasIdIndexRouteImport
      parentRoute: typeof ArchitectureCanvasIdRoute
    }
    '/learnings/files/$folderId': {
      id: '/learnings/files/$folderId'
      path: '/files/$folderId'
      fullPath: '/learnings/files/$folderId'
      preLoaderRoute: typeof LearningsFilesFolderIdRouteImport
      parentRoute: typeof LearningsRoute
    }
    '/learnings/docs/$docId': {
      id: '/learnings/docs/$docId'
      path: '/docs/$docId'
      fullPath: '/learnings/docs/$docId'
      preLoaderRoute: typeof LearningsDocsDocIdRouteImport
      parentRoute: typeof LearningsRoute
    }
    '/learnings/blogs/$blogId': {
      id: '/learnings/blogs/$blogId'
      path: '/blogs/$blogId'
      fullPath: '/learnings/blogs/$blogId'
      preLoaderRoute: typeof LearningsBlogsBlogIdRouteImport
      parentRoute: typeof LearningsRoute
    }
    '/learnings/blogs/create': {
      id: '/learnings/blogs/create'
      path: '/blogs/create'
      fullPath: '/learnings/blogs/create'
      preLoaderRoute: typeof LearningsBlogsCreateRouteImport
      parentRoute: typeof LearningsRoute
    }
    '/learnings/blogs/$blogId/edit': {
      id: '/learnings/blogs/$blogId/edit'
      path: '/blogs/$blogId/edit'
      fullPath: '/learnings/blogs/$blogId/edit'
      preLoaderRoute: typeof LearningsBlogsBlogIdEditRouteImport
      parentRoute: typeof LearningsRoute
    }
    '/learnings/docs/create': {
      id: '/learnings/docs/create'
      path: '/docs/create'
      fullPath: '/learnings/docs/create'
      preLoaderRoute: typeof LearningsDocsCreateRouteImport
      parentRoute: typeof LearningsRoute
    }
    '/learnings/docs/$docId/edit': {
      id: '/learnings/docs/$docId/edit'
      path: '/docs/$docId/edit'
      fullPath: '/learnings/docs/$docId/edit'
      preLoaderRoute: typeof LearningsDocsDocIdEditRouteImport
      parentRoute: typeof LearningsRoute
    }
    '/architecture/view/$viewerId': {
      id: '/architecture/view/$viewerId'
      path: '/architecture/view/$viewerId'
      fullPath: '/architecture/view/$viewerId'
      preLoaderRoute: typeof ArchitectureViewViewerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/architecture/$canvasId/edit': {
      id: '/architecture/$canvasId/edit'
      path: '/edit'
      fullPath: '/architecture/$canvasId/edit'
      preLoaderRoute: typeof ArchitectureCanvasIdEditRouteImport
      parentRoute: typeof ArchitectureCanvasIdRoute
    }
  }
}

interface LearningsRouteChildren {
  LearningsBlogsBlogIdRoute: typeof LearningsBlogsBlogIdRoute
  LearningsBlogsCreateRoute: typeof LearningsBlogsCreateRoute
  LearningsBlogsBlogIdEditRoute: typeof LearningsBlogsBlogIdEditRoute
  LearningsDocsDocIdRoute: typeof LearningsDocsDocIdRoute
  LearningsDocsCreateRoute: typeof LearningsDocsCreateRoute
  LearningsDocsDocIdEditRoute: typeof LearningsDocsDocIdEditRoute
  LearningsFilesFolderIdRoute: typeof LearningsFilesFolderIdRoute
}

const LearningsRouteChildren: LearningsRouteChildren = {
  LearningsBlogsBlogIdRoute: LearningsBlogsBlogIdRoute,
  LearningsBlogsCreateRoute: LearningsBlogsCreateRoute,
  LearningsBlogsBlogIdEditRoute: LearningsBlogsBlogIdEditRoute,
  LearningsDocsDocIdRoute: LearningsDocsDocIdRoute,
  LearningsDocsCreateRoute: LearningsDocsCreateRoute,
  LearningsDocsDocIdEditRoute: LearningsDocsDocIdEditRoute,
  LearningsFilesFolderIdRoute: LearningsFilesFolderIdRoute,
}

const LearningsRouteWithChildren = LearningsRoute._addFileChildren(
  LearningsRouteChildren,
)

interface ArchitectureCanvasIdRouteChildren {
  ArchitectureCanvasIdEditRoute: typeof ArchitectureCanvasIdEditRoute
  ArchitectureCanvasIdIndexRoute: typeof ArchitectureCanvasIdIndexRoute
}

const ArchitectureCanvasIdRouteChildren: ArchitectureCanvasIdRouteChildren = {
  ArchitectureCanvasIdEditRoute: ArchitectureCanvasIdEditRoute,
  ArchitectureCanvasIdIndexRoute: ArchitectureCanvasIdIndexRoute,
}

const ArchitectureCanvasIdRouteWithChildren =
  ArchitectureCanvasIdRoute._addFileChildren(ArchitectureCanvasIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GameRoute: GameRoute,
  LearningsRoute: LearningsRouteWithChildren,
  ArchitectureCanvasIdRoute: ArchitectureCanvasIdRouteWithChildren,
  ArchitectureViewViewerIdRoute: ArchitectureViewViewerIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
