/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LearningsRouteImport } from './routes/learnings'
import { Route as IndexRouteImport } from './routes/index'

const LearningsRoute = LearningsRouteImport.update({
  id: '/learnings',
  path: '/learnings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/learnings': typeof LearningsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/learnings': typeof LearningsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/learnings': typeof LearningsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/learnings'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/learnings'
  id: '__root__' | '/' | '/learnings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LearningsRoute: typeof LearningsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/learnings': {
      id: '/learnings'
      path: '/learnings'
      fullPath: '/learnings'
      preLoaderRoute: typeof LearningsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LearningsRoute: LearningsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
