/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LearningsRouteImport } from './routes/learnings'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArchitectureCanvasIdRouteImport } from './routes/architecture.$canvasId'
import { Route as LearningsFilesFolderIdRouteImport } from './routes/learnings.files.$folderId'
import { Route as LearningsDocsDocIdRouteImport } from './routes/learnings.docs.$docId'
import { Route as LearningsBlogsBlogIdRouteImport } from './routes/learnings.blogs.$blogId'
import { Route as ArchitectureViewViewerIdRouteImport } from './routes/architecture.view.$viewerId'
import { Route as ArchitectureCanvasIdEditRouteImport } from './routes/architecture.$canvasId.edit'

const LearningsRoute = LearningsRouteImport.update({
  id: '/learnings',
  path: '/learnings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchitectureCanvasIdRoute = ArchitectureCanvasIdRouteImport.update({
  id: '/architecture/$canvasId',
  path: '/architecture/$canvasId',
  getParentRoute: () => rootRouteImport,
} as any)
const LearningsFilesFolderIdRoute = LearningsFilesFolderIdRouteImport.update({
  id: '/files/$folderId',
  path: '/files/$folderId',
  getParentRoute: () => LearningsRoute,
} as any)
const LearningsDocsDocIdRoute = LearningsDocsDocIdRouteImport.update({
  id: '/docs/$docId',
  path: '/docs/$docId',
  getParentRoute: () => LearningsRoute,
} as any)
const LearningsBlogsBlogIdRoute = LearningsBlogsBlogIdRouteImport.update({
  id: '/blogs/$blogId',
  path: '/blogs/$blogId',
  getParentRoute: () => LearningsRoute,
} as any)
const ArchitectureViewViewerIdRoute =
  ArchitectureViewViewerIdRouteImport.update({
    id: '/architecture/view/$viewerId',
    path: '/architecture/view/$viewerId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ArchitectureCanvasIdEditRoute =
  ArchitectureCanvasIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => ArchitectureCanvasIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/learnings': typeof LearningsRouteWithChildren
  '/architecture/$canvasId': typeof ArchitectureCanvasIdRouteWithChildren
  '/architecture/$canvasId/edit': typeof ArchitectureCanvasIdEditRoute
  '/architecture/view/$viewerId': typeof ArchitectureViewViewerIdRoute
  '/learnings/blogs/$blogId': typeof LearningsBlogsBlogIdRoute
  '/learnings/docs/$docId': typeof LearningsDocsDocIdRoute
  '/learnings/files/$folderId': typeof LearningsFilesFolderIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/learnings': typeof LearningsRouteWithChildren
  '/architecture/$canvasId': typeof ArchitectureCanvasIdRouteWithChildren
  '/architecture/$canvasId/edit': typeof ArchitectureCanvasIdEditRoute
  '/architecture/view/$viewerId': typeof ArchitectureViewViewerIdRoute
  '/learnings/blogs/$blogId': typeof LearningsBlogsBlogIdRoute
  '/learnings/docs/$docId': typeof LearningsDocsDocIdRoute
  '/learnings/files/$folderId': typeof LearningsFilesFolderIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/learnings': typeof LearningsRouteWithChildren
  '/architecture/$canvasId': typeof ArchitectureCanvasIdRouteWithChildren
  '/architecture/$canvasId/edit': typeof ArchitectureCanvasIdEditRoute
  '/architecture/view/$viewerId': typeof ArchitectureViewViewerIdRoute
  '/learnings/blogs/$blogId': typeof LearningsBlogsBlogIdRoute
  '/learnings/docs/$docId': typeof LearningsDocsDocIdRoute
  '/learnings/files/$folderId': typeof LearningsFilesFolderIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/learnings'
    | '/architecture/$canvasId'
    | '/architecture/$canvasId/edit'
    | '/architecture/view/$viewerId'
    | '/learnings/blogs/$blogId'
    | '/learnings/docs/$docId'
    | '/learnings/files/$folderId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/learnings'
    | '/architecture/$canvasId'
    | '/architecture/$canvasId/edit'
    | '/architecture/view/$viewerId'
    | '/learnings/blogs/$blogId'
    | '/learnings/docs/$docId'
    | '/learnings/files/$folderId'
  id:
    | '__root__'
    | '/'
    | '/learnings'
    | '/architecture/$canvasId'
    | '/architecture/$canvasId/edit'
    | '/architecture/view/$viewerId'
    | '/learnings/blogs/$blogId'
    | '/learnings/docs/$docId'
    | '/learnings/files/$folderId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LearningsRoute: typeof LearningsRouteWithChildren
  ArchitectureCanvasIdRoute: typeof ArchitectureCanvasIdRouteWithChildren
  ArchitectureViewViewerIdRoute: typeof ArchitectureViewViewerIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/learnings': {
      id: '/learnings'
      path: '/learnings'
      fullPath: '/learnings'
      preLoaderRoute: typeof LearningsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/architecture/$canvasId': {
      id: '/architecture/$canvasId'
      path: '/architecture/$canvasId'
      fullPath: '/architecture/$canvasId'
      preLoaderRoute: typeof ArchitectureCanvasIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learnings/files/$folderId': {
      id: '/learnings/files/$folderId'
      path: '/files/$folderId'
      fullPath: '/learnings/files/$folderId'
      preLoaderRoute: typeof LearningsFilesFolderIdRouteImport
      parentRoute: typeof LearningsRoute
    }
    '/learnings/docs/$docId': {
      id: '/learnings/docs/$docId'
      path: '/docs/$docId'
      fullPath: '/learnings/docs/$docId'
      preLoaderRoute: typeof LearningsDocsDocIdRouteImport
      parentRoute: typeof LearningsRoute
    }
    '/learnings/blogs/$blogId': {
      id: '/learnings/blogs/$blogId'
      path: '/blogs/$blogId'
      fullPath: '/learnings/blogs/$blogId'
      preLoaderRoute: typeof LearningsBlogsBlogIdRouteImport
      parentRoute: typeof LearningsRoute
    }
    '/architecture/view/$viewerId': {
      id: '/architecture/view/$viewerId'
      path: '/architecture/view/$viewerId'
      fullPath: '/architecture/view/$viewerId'
      preLoaderRoute: typeof ArchitectureViewViewerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/architecture/$canvasId/edit': {
      id: '/architecture/$canvasId/edit'
      path: '/edit'
      fullPath: '/architecture/$canvasId/edit'
      preLoaderRoute: typeof ArchitectureCanvasIdEditRouteImport
      parentRoute: typeof ArchitectureCanvasIdRoute
    }
  }
}

interface LearningsRouteChildren {
  LearningsBlogsBlogIdRoute: typeof LearningsBlogsBlogIdRoute
  LearningsDocsDocIdRoute: typeof LearningsDocsDocIdRoute
  LearningsFilesFolderIdRoute: typeof LearningsFilesFolderIdRoute
}

const LearningsRouteChildren: LearningsRouteChildren = {
  LearningsBlogsBlogIdRoute: LearningsBlogsBlogIdRoute,
  LearningsDocsDocIdRoute: LearningsDocsDocIdRoute,
  LearningsFilesFolderIdRoute: LearningsFilesFolderIdRoute,
}

const LearningsRouteWithChildren = LearningsRoute._addFileChildren(
  LearningsRouteChildren,
)

interface ArchitectureCanvasIdRouteChildren {
  ArchitectureCanvasIdEditRoute: typeof ArchitectureCanvasIdEditRoute
}

const ArchitectureCanvasIdRouteChildren: ArchitectureCanvasIdRouteChildren = {
  ArchitectureCanvasIdEditRoute: ArchitectureCanvasIdEditRoute,
}

const ArchitectureCanvasIdRouteWithChildren =
  ArchitectureCanvasIdRoute._addFileChildren(ArchitectureCanvasIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LearningsRoute: LearningsRouteWithChildren,
  ArchitectureCanvasIdRoute: ArchitectureCanvasIdRouteWithChildren,
  ArchitectureViewViewerIdRoute: ArchitectureViewViewerIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
